# Research practices {#research}

## Data management and coding

The Gaynor Lab is committed to principles of reproducible science. Our primary coding language is R, although you are encouraged to explore other tools that better fit your needs (and teach the rest of us!). 

All data cleaning and analysis should be conducted in scripts. There will be a learning curve at first, and you'll be tempted to open up your data files and manipulate them in Excel, but the time investment in learning how to wrangle data in R will pay off in the long run.

Code should be complete and well-documented, including information in a README about what each file does and the workflow to run the code.

### GitHub for project management

We use GitHub for managing research projects. We have a [lab GitHub organization](https://github.com/gaynor-lab), which you should join upon entry to the lab. You may create repositories in your personal GitHub pages for regular thesis research work, but all repositories should be forked to the organization upon project completion or hand-off.

In general, one repository should correspond to one thesis chapter/publication, although there are cases where lumping or splitting repositories makes more sense. Create your project repository as soon as you begin managing your data. 

You are encouraged to regularly commit all of your code to GitHub, on a daily basis. If it works for you, treat your commit messages and GitHub issues as your lab notebook. This may feel vulnerable, especially for those learning to code, but this is a judgment-free zone and there is no better way to learn than to code collaboratively. The use of GitHub makes it very easy to share feedback with other lab members on coding and analysis.

By the time of completion, each project should have an easily found README text file that provides information for others so they can navigate and use your work, and give contact information for authors (and any data creators/use restrictions if proprietary data). Ideally, the README should also include links to publications and presentations from the work.

### Data management

Data used in support of your projects should be:

* Saved in appropriate, non-proprietary format with accompanying metadata
* Either in a public archive (e.g., the github repo or another public archive), or if data is proprietary, a 'snapshot' version of the data used in the project should be saved in a private repository accessible to lab members. Alternatively, data could be saved on the lab_fay server drive with appropriate documentation. 
* Linked and briefly described in the project README.

The average life expectancy of a hard drive is less than the duration of most graduate programs. Thus it is critical to ensure your data and work are backed up regularly. You may have personal backup solutions (e.g. through Dropbox, Google Drive, etc.) but the lab has dedicated storage space on a university server that is backed up in multiple locations. Your data should be backed up on here. *Include information on how to do this* 

### Resources for learning R

*From the [Faylab Lab Manual](https://thefaylab.github.io/lab-manual/)*

Welcome to `R`! There are so many learning resources out there it can feel a little overwhelming in terms of what to choose! To get you set up and started, [Happy Git and Github for the useR](https://happygitwithr.com/) is a great resource, and is created by the same authors as the now-legendary [stat545.com](stat545.com) course. Their resources are extremely comprehensive and they have a fantastic Intro R course, especially for those who will be using R for doing statistics.   

Right now, we REALLY like [this short intro course](https://rstudio-conf-2020.github.io/r-for-excel/) by [`@juliesquid`](https://twitter.com/juliesquid) & [`@allisonhorst`](https://twitter.com/allisonhorst). They teach a lot of the workflow and tools around using R right from the get go, which we think is more helpful than knowing how to do all the things. The (excellent) materials are thoughtfully put together, link to a ton of other great resources, and just like the online #rstats community in general, are super supportive of new learners. We also really like the [Teacup Giraffes](https://tinystats.github.io/teacups-giraffes-and-statistics/index.html) R and statistics materials from Desirée De Leon and Hasse Walum.   

If you want a book to work from/through, [R for Data Science](r4ds.had.co.nz) is highly recommended.  (book is free online)  

The [R Studio Education](https://education.rstudio.com/) team have assembled a phenomenal array of courses, tutorials, and other materials for learning R, and for many types of data analyses and modeling using R. These are top notch and so thoughtfully put together. There is something for learners at all levels.  

A plug for the online R community. Follow the hashtag #rstats, & also check out accounts [`@RLadiesGlobal`](https://twitter.com/RLadiesGlobal) & [`@R4dsCommunity`](https://twitter.com/R4dsCommunity). The weekly #TidyTuesday social coding project is also a great way to practice your growing R skills. Have fun!  

The R4dsCommunity Slack is a briliant resource for getting help to your R questions and finding tutorials. They also hold online Office Hours where you can get help with R from a real human.  

The [RStudio Community](https://community.rstudio.com/) is a great go-to.  

Learn R from within R with interactive sessions using [swirlstats.com](swirlstats.com).  

The [carpentries R lessons](https://datacarpentry.org/R-ecology-lesson/) are also a fab resource.  



## Writing and reading practices

### Formats

We won't micromanage individual writing processes, but Kaitlyn prefers to provide feedback in Microsoft Word (especially for longer pieces) or Google Docs

### Reference management

Find a reference management system that works for you, if you don't already have one, and start using it early in your time in the Gaynor Lab to organize papers as you read them.

We will likely use Zotero for shared group writing projects, as it is free and easy to use, but you may find another system you prefer for your own research.

It is a good idea to develop a system for staying on top of the relevant literature in your field and subfields, which may include the following practices:
+ Set Google Scholar alerts for keywords or authors
+ Create an RSS feed for journals in your field
+ Subscribe to e-mail updates for journal tables of contents