# Advising and mentorship {#advising}

## NSERC mentorship statement

*This is the mentorship statement that I (Kaitlyn) wrote as part of the application for the 2022 NSERC Discovery Grant that funds our work. I share it here so that all lab members know where I am coming from:*

Once students are in my group, I will adopt an individualized approach to mentoring. Through Individualized Mentoring Plans, I will help students articulate their own measurable and achievable goals and areas for improvement each year, and we will review these plans at the start of each term. I will maintain open lines of communication and check in on progress in weekly 30-minute meetings to hold lab members accountable to themselves, rather than to me, and to ensure that their experience at UBC best prepares them for their desired career.

The mentor-mentee relationship must be grounded in mutual respect. I keep an open mind and appreciate the diverse ways of knowing that trainees bring to the table. I will regularly clarify mutual expectations so we are on the same page on subjects such as communication, feedback on materials, and funding. While fostering this mutual respect, I will respect boundaries and acknowledge the power dynamics inherent to the relationship.

I will help students to build confidence and skills to meet their goals, including diverse and tailored skill sets in research, science communication, data science, and outreach. I will empower students to take ownership of their work, and cultivate a culture that applauds risk-taking and normalizes failure. Furthermore, it is important to help students not only navigate systems but help them to change them, particularly for students from historically-excluded groups, and I plan to support them in their efforts to make our departments at UBC more inclusive. I also recognize that some students face identity prejudice in the field, which can place them in unsafe and uncomfortable positions, and I will create guidance for fieldwork that promotes safety and belonging.

To advance research and training goals, I will foster community and belonging among the research group so that students can lean on each other for support, and not feel that they are competing for my attention or resources. We will share responsibilities for organizing weekly lab meetings, annual lab retreats, collaborative research projects, social events, and lab logistics, and co-create a lab code of conduct to ensure our work and culture are inclusive, feminist, and anti-racist. Students from equity-seeking groups at UBC report less positive experiences, and I will make efforts to align the goals of my research group with those identified in the 2018 UBC Inclusion Action Plan (e.g., develop flexible research practices to accommodate diverse needs; build capacity through skills training; recognize and incentivize DEI activities). I recognize that I will not share all of the same life experiences and challenges as the members of my group, and will therefore encourage students to connect with others in the departments and community for support (e.g., EDI for Trainees in Zoology, UBC Equity and Inclusion Office).

Within my research group and larger communities at UBC, I will promote self-education and conversation around difficult topics related to justice, equity, and inclusion. There are also small but important steps that I will take to create an inclusive culture, including indigenous land acknowledgements, pronoun sharing, and the creation of accessible learning materials and infrastructure. Part of creating an inclusive culture starts with bringing our full selves to the table, and talking about how our identities shape our positionality as researchers and our experiences working with agencies and stakeholders.


## Individual mentoring plans

Within the first few weeks of joining the Gaynor Lab, you should work with Kaitlyn to develop a plan outlining your short, medium, and long term goals. This is a useful planning document that assists in aligning expectations. Each lab member will revisit the mentoring plan during an individual meeting with Kaitlyn at the beginning of each semester.

A template for graduate student mentoring plans can be found [here](https://docs.google.com/document/d/1GVBybwqujkrSIRqcw5gzAcOnCivtmA1vTVmi478Prrg/edit?usp=sharing), and is adapted from [Stanford's Office of Graduate Education](https://oge.stanford.edu/academics/idp/forms/).

A template for undergraduate student mentoring plans can be found [here](https://docs.google.com/document/d/1nAVETDDRoxIKijQ9AmSYATWZO3svhAzv_jWBnZF7aw4/edit?usp=sharing).

In addition to these individualized plans, which will guide specific self-defined expectations, Chapter \@ref(expectations) clarifies expectations for all lab members in their interactions with Kaitlyn.

### For undergraduate lab members

You may be working most closely with a graduate student or postdoc in the Gaynor Lab, in which case they will be your primary source of contact. You should work with them to establish and define your work schedule, protocols for your work, and to ensure you have the necessary equipment to perform your work tasks.  

Always feel like you can reach out to both [Kaitlyn](mailto:kaitlyn.gaynor@ubc.ca) as lab PI. We are excited to help you use your position in the lab to further your career goals and want to work with you to help you achieve them.


## UBC expectations

UBC has outlined [detailed guidance](https://responsible.research.ubc.ca/foundations/mentorship-supervision) for mentorship and supervision, including the following expectations for supervisors of graduate students. More details about Gaynor Lab policies on the points below can be found elsewhere in this manual, as linked below.

For graduate students, as your supervisor, you can expect me to:

+ Demonstrate commitment to your research and educational program, and offer stimulation, respectful support, constructive criticism, and consistent encouragement.
+ Assist with identification of a research topic that is suitable for you and manageable within the scope of your degree.
+ Have sufficient familiarity with your field of research to provide guidance as a supervisor.
+ Assist you in gaining access to required facilities or research materials for your projects.
+ Discuss your financial support issues and assist with scholarship applications and/or providing advice on academic employment opportunities.
+ Provide guidance in the ethical conduct of research and model research integrity.
+ Discuss with you the implications of engaging with activities/work unrelated to your thesis topic.
+ Provide information about my availability for meetings and expectations about preparation for meetings. 
+ Assist you in planning your research program, setting a time frame, and adhering as much as possible to the schedule.  
+ Encourage you to finish up when it would not be in your best interest to stay longer.
+ Be accessible for consultation and discussion of your academic progress and research at a minimum of once a term.
+ Minimize my expectations for activities/work that may interfere with your thesis completion.
+ Institute a supervisory committee (with appropriate input from you) and prepare for committee meetings, which will occur on a regular basis (at least once a year) to review your progress and provide guidance for your future work.
+ Support you in your preparation for the comprehensive examination and admission to candidacy which will be completed within 36 months of program initiation.
+ Act as a resource about managing program requirements, deadlines, etc.
+ Attend your presentations in appropriate venues and join in associated discussion.
+ Submit recommendations for external examiners and university examiners for the doctoral dissertation within the time frames required by the Faculty of Graduate and Postdoctoral Studies.
+ Acknowledge your contributions, when appropriate, in published material and oral presentations in accordance with good scholarly practice and the University of British Columbia scholarly integrity policies.
+ Provide reasonable expectations about work day hours and vacation time in accordance with University of British Columbia policies.  
+ Clarify my preferred style of communication with students about areas, such as student independence, approaches to conflict, direct questioning, and mentoring.
+ Explain my expectations for mode of address, professional behaviour (e.g. punctuality), when to seek assistance, response to constructive criticism, and academic performance expectations.
+ Assist you to overcome any cultural difficulties with norms and expectations. 
+ Respond thoroughly (with constructive suggestions for improvement) and in a timely fashion to submitted, written work.
+ Promote a research environment that is safe and free from harassment.
+ Assist in managing conflict or differences among members of the supervisory committee.
+ Make arrangements to ensure adequate supervision if I am absent for extended periods, e.g. more than a month.
+ Encourage you to present your research results within and outside the University.
+ Provide mentoring in academic writing.
+ Provide advice and mentorship with respect to career opportunities, which may be assisted by resources, skills, professional development, and other avenues.

I (Kaitlyn) will make every effort to meet these expectations for each member of the lab, although I acknowledge that I am human, and still learning to navigate my position as a new P.I., and sometimes things may unintentionally slip through the cracks. If you find that I am not meeting these expectations, please bring up your questions or concerns sooner than later (ideally in our individual meetings, or via e-mail if more comfortable) so that we can talk through them, clarify mutual expectations, course-correct, and ensure the situation improves rather than worsens. Feel free to refer back to this lab manual.

## Committee member expectations

This guidance is intended for graduate students who have me (Kaitlyn) on their committees, or who are interested in having me serve on their committee. Serving on graduate student committees is one of the most enjoyable and rewarding responsibilities of my job! I really enjoy the opportunity to dive into a diversity of research topics, learn about new disciplines, and lend expertise and advice when relevant. To allow us to get the most out of the student-committee member relationship, I am laying out some general expectations, which we can discuss and adapt according to your individual needs. Ultimately, this guidance will enable me to be the best possible committee member (I hope!). 

#### What I expect of you:

+ Touch base with me at least once a year (ideally once a term), even if just a quick e-mail to let me know where you're at, and what's on the horizon.
+ Plan to check in with me before embarking on a major aspect of your project (e.g., data collection), either during committee meetings, one-on-one meetings, or via e-mail. This will allow me to give constructive feedback on study design before you have invested a significant amount of time!
+ Please allow me to provide feedback on your chapters prior to submission for peer-reviewed publication. My feedback becomes significantly less relevant to the greater scientific enterprise once a paper has been published!
+ Check in with me several months ahead of large milestones (comprehensive exams, proposal defense, chapter draft completion) so that I can advise you of any limitations in my availability due to fieldwork, vacation, conferences, etc.
+ Please give me a heads up about when you plan to send written material for feedback. If you give me at least two weeks notice that you will be sending me written material to review, I can plan for it, and turn it around within 2-3 days (assuming I'm not out of the office). Without advanced notice, I'll probably need 2 weeks.
+ When asking for feedback on written material, please let me know what kind of feedback would be most useful (do you want me to comment on high-level ideas, writing, copy editing, figure design, etc.) and if there are particular areas that you would like me to focus my attention (either given my expertise, or given where you feel the greatest need for feedback).
+ For comprehensive exams, please discuss reading lists with me several months in advance. You should brainstorm a list of topics and some papers you may be interested in reading, and I can riff off of this list and make suggestions (generally, I recommend an even mix of "classic"/foundational papers, recent reviews/syntheses/perspectives/chapters, and cutting-edge empirical studies)
+ I do not expect coauthorship on papers arising from your thesis, unless we have discussed otherwise. An acknowledgement is always appreciated if I've earned it, which I hope to :)

#### What you can expect of me:

+ I will keep an open mind so that I may learn from you and the other members of your committee.
+ I will give thoughtful feedback on your proposals and chapters on an annual basis, or more frequently if needed, either during meetings or in writing. This feedback will be timely, assuming ample advance notice as discussed above.
+ Prior to your comprehensive exams, I would be happy to have a couple of informal meetings to discuss the readings in a less stressful way, and think through ideas they raise together, as they relate to your thesis. These conversations will likely be far more productive than the weird question-and-answer of the exam, and allow you to get the most out of the exam process.
+ If my level of engagement is rising to the level of a coauthor/collaborator (something that we should determine in consultation with your primary advisor), you can expect me to provide an even higher level of contribution (more direct edits to writing, code contributions, greater intellectual engagement, more frequent meetings, etc.) and not just ride your coat-tails!
+ I will make every effort to be constructive, empathetic, and reasonable, and will respect you as the ultimate decision-maker with regard to your own research.
+ I will be honest about my limitations, either in my time or expertise, and try to direct you to outside resources that may be able to fill in any gaps.
+ If you are interested in talking more broadly about professional development or careers, I will make myself available for those conversations.
+ I will loop you into any opportunities for collaboration, presentations, or student mentoring that align with your interests.
+ I will respond to e-mails quickly, and clearly communicate expectations to you (see above!)


