# Lab member expectations {#expectations}

All lab members are expected to adhere to our lab philosophy (Chapter \@ref(philosophy)), communication practices (Chapter \@ref(communication)), research practices (Chapter \@ref(research)), and fieldwork policies (Chapter \@ref(fieldwork)), as outlined elsewhere in this manual.


## UBC requirements

Given that our lab members have diverse departmental affiliations and are enrolled in various programs, with various funding arrangements, it is the responsibility of the individual lab member to ensure they are keeping on top of paperwork related to their own payroll, HR, travel, reimbursements, etc. We can use this lab manual and lab Slack to share information and resources with one another, and please let Kaitlyn know if you have questions or need support.

Graduate students are responsible for degree progress. This means you need to stay on top of program and university deadlines, requirements, etc. Before registering for courses each term, you should discuss your plans with Kaitlyn (ideally in our weekly meetings).

Resources:

+ [Zoology Graduate Student Handbook](https://www.zoology.ubc.ca/system/files/assets/media-file/file/2022-03/New%20Handbook%202022_March.pdf)
+ [UBC Graduate Game Plan](https://www.grad.ubc.ca/current-students/professional-development/graduate-game-plan)

## Research

The level of independence of lab members in research development will vary according to position, with increasing independence from undergraduate to MSc to PhD to postdocs, and will increase over the course of an individual's time in the lab. 

For all graduate students and postdocs, it is expected that research is your top priority during your time in the Gaynor Lab. In addition to following our lab research practices (Chapter \@ref(research)), you should plan to publish your work in peer-reviewed journals and present it at scientific conferences. Communication of your approach and findings is an essential step in the scientific process.

### Publication

Graduate students should plan to submit half of their chapters to peer-reviewed journals prior to sign-off on their thesis. For PhD students, aim to submit one chapter to both your committee and a peer-reviewed publication within the first 3.5 years in the program, and a second within the first 5.

Kaitlyn and other lab members will support you in navigating the peer-review process, including journal selection, responses to reviewers, and payment of publication costs.

When you leave the lab, make a plan with Kaitlyn for the timeline and process of submission of any additional first-authored papers from your time in the lab. If your plans change and you can no longer commit to the publication process on the timeline that we discussed, other members of the Gaynor Lab will be given the opportunity to follow through on the work (with credit given to your contributions, of course). Kaitlyn will talk to you to make a plan well before we reach this point.


### Conferences

Members of the Gaynor Lab are expected to share our research at local, national, and international meetings. We will share information with each other on upcoming conferences, and provide feedback on drafts of posters and presentations in lab meeting.

To ensure that we are on the same page when sharing in-progress work with the public and with the scientific community, you should clear any abstracts and slideshows with Kaitlyn and other co-authors. Ideally, you'll give a practice presentation in a lab meeting, too!

Discuss your conference interests with Kaitlyn, and prepare a budget and justification (what will you gain by participating, what will you be presenting?). It is our goal that everyone should be able to participate in at least one local or regional conference each year (e.g. BCTWS) and one national or international conference at least once during their degree.

The Faculty of Graduate and Postdoctoral Studies gives graduate students up to $500 to reimburse travel costs through the [Graduate Student Travel Fund](https://www.grad.ubc.ca/awards/graduate-student-travel-research-dissemination-fund), once per degree program. Obtaining reimbursements may take up to 4-8 weeks during peak times. 

### Authorship policy

In our collaborative work, the person who makes the most significant intellectual contributions (in terms of conceiving the original idea, method development, experiment design, analysis) and leads the research and writing of the manuscript will be the first author.

Shared first authorship may be an option in some circumstances: for example, when projects are truly co-developed and done equally, or when leadership of a project is handed off from one lab member to another upon leaving the group. However, graduate students should plan to be the sole first author on any papers that arise from thesis chapters.

Co-authorship on a paper can be earned through substantial intellectual contribution (e.g., development of ideas, interpretation of results) or contribution to data collection, analysis, and/or writing. Contribution of data alone does not usually merit authorship, but data contributors should be given the opportunity to be co-authors by providing additional contributions. All coauthors should be involved in the writing process by giving feedback on drafts.

If you are leading a project that is facilitated by undergraduate researchers and/or field technicians, you are encouraged to provide these individuals with the opportunity to contribute intellectually to the project and earn co-authorship.

It is likely that Kaitlyn will be the last (senior) author on most publications led by lab members for research that is primarily conducted while you are in the lab. However, like all co-authors, Kaitlyn should earn this authorship position! Generally, you should maintain open lines of communication with Kaitlyn about your publication plans, so that she can best support you and navigate coauthorship discussions. For papers on which you are the first author and Kaitlyn is last author, the two of you should plan to make collective decisions about the authorship of others. 

In general, discuss authorship with your colleagues early in the collaboration process, to ensure alignment of expectations and a positive working relationship. The invitation of co-authorship should be made explicitly and in writing.

As always, feel free to ask Kaitlyn if you have any concerns or questions about authorship, either of work that you are leading or work on which you expect to be a coauthor. There are many gray areas and unique cases.

## Funding


The Zoology minimum graduate student stipend is $30,000 annually (including tuition and student fees). The funds to support this stipend do not come from the department or the lab, however, and the stipend is comprised of a combination of TA-ships, fellowships, and GRAs. The exact breakdown will vary by student. This minimum stipend will apply to all students in the lab, regardless of home department (unless the home department has a higher minimum, although as of now, that is not the case for any lab members). In the Gaynor Lab, graduate students can expect a stipend of $30,000 PLUS tuition for 5 years of a PhD and 2 years of a MSc, contingent on availability of lab research funds to cover tuition, and satisfactory degree progress. Please note that students in many departments are also expected to pay [student fees](https://students.ubc.ca/enrolment/finances/tuition-fees), which are paid out of the stipend.

**Fellowships**: All lab members are expected to seek and apply for extramural funding to support their work. This includes scholarships and fellowships to go towards their $30,000 stipend (e.g., 4YF, NSERC), but also smaller grants for travel, workshop attendance, or research costs. As a general rule, all graduate students should apply for at least one grant or fellowship every year. In most cases, obtaining a fellowship will not increase the overall take-home pay for the student, but may reduce the need to TA (see details below), and will free up lab funds to support student research, travel, and conference attendance.

**TA-ships**: Graduate students are expected to TA for two terms each year, by default. If a student has fellowship support >$15,000, they are expected to TA for at least one term. Students with fellowship(s) totaling over $30,000 may choose whether or not to TA, with all TA funding going to them.

**GRAs**: We will use lab funds (GRAs or work-learn positions) to bring take-home salaries to $30,000, so long as a student is making satisfactory progress towards degree. These funds should be considered a last resort, after fellowships, TAships, and other funding opportunities have been exhausted. If you are funded from lab grants and contracts, you may need to be flexible in your research and adjust the topic to better align with the current grants/contracts that we have in the lab. If you are funded through a work-learn position, you may be asked to do a small amount of non-research work in service of broader lab goals (e.g., event planning, administrative work).

**Bonus**: Students who earn $24,000 or more through a combination of fellowship and TAships will receive an additional $1,500 bonus on top of the standard GRA, bringing their stipend to $31,500 (or higher, if combined fellowships and TA-ships exceed $30,000). This is in an attempt to keep things reasonably fair amongst students in the lab, while still incentivizing TAing and applying for fellowships beyond what is needed to meet the minimum.

Graduating students and postdoctoral researchers are also encouraged to apply for funding to support their next steps.


## Community engagement

### Service and outreach

All members of the Gaynor Lab should dedicate time to serving our communities—the lab, the departments, the university, the scientific community, and the other communities of which we are a part. Creating and giving back to community is important in building and maintaining relationships, and can also help to hone leadership and professional development skills.

This service will look different for each lab member, and ideally should align with the goals that are articulated in Individual Development plans. For example, your service may be oriented towards equity and justice work, event planning, science communication, capacity building, etc. We will support each other in our service work and ensure that this work is recognized and valued.

Everybody should recognize that service burdens fall disproportionately on members of underrepresented groups. We should consider how our individual identities may shape the way that we approach service responsibilities and adjust our approaches accordingly. 

If service work is being done at the expense of satisfactory progress towards degrees and/or research, Kaitlyn will reach out to initiate a conversation about how to best balance responsibilities to align with your goals.

### Responsibilities to lab

Within the Gaynor Lab, we will assign each individual rotating roles annually, so that we share responsibilities and investment in our research group. These responsibilities may include organizing lab meetings, maintaining the lab website and manual, cleaning physical lab space, etc.

Everybody in the Gaynor Lab should seek to provide mentorship, technical support, and assistance to other lab members, especially more senior members of the group.

### Attendance and participation

All lab members are expected to attend lab meetings, BRC and departmental seminars, and lab member defenses. We should all make an effort to attend social events put on by the lab, BRC, and departments, especially those within normal work hours. 

We are all busy, and there will always be something to do that feels more "productive" or urgent than attending a seminar or social event, but we should all recognize that these events are critical for building community. Ultimately, investment in relationships in our professional community will build a network to uplift and support our research, set the groundwork for new collaborations, and lead to new professional opportunities.

Even if a talk is outside of your area of interest, use it as an opportunity to reflect on effective (and ineffective) presentation approaches.

## Work schedule

### Work hours

We should all set the working schedule that is the right fit for us, and it is likely that what this 'fit' is will change over the course of the time you are in the lab. Depending on the nature of your appointment, there may be specific hours that will need to be worked and you should work with your main collaborator to outline these. 

There is value to interacting with others as part of your work, and we do expect you will be available during normal working hours for at least some of the time during the week. Lab members should not expect others to be available during evenings and weekends. We also recognize that there will occasionally be times where there is a need to work more to meet a deadline, but this should be the exception - an expectation of overwork is not to be normalized.

### Time budgeting

For graduate students and postdocs, plan to spend 40 hours/week actively working on research, teaching, and professional development activities. The exact breakdown of this time will depend on the nature of your appointment (e.g., TA and RA positions). Some people find that tracking hours is productive for them as it helps them keep accountable to themselves (Kaitlyn uses [Toggl](https://toggl.com) for this purpose). Others do not find this method useful. Regularly assess what works best for you.  

### Vacation

Graduate students may take 15 weekdays of vacation, as per [UBC policy](https://www.grad.ubc.ca/current-students/managing-your-program/graduate-student-vacation-policy). You are not expected to be engaged in research or in communication with the lab while you are on vacation.

There is no formal system for tracking vacation, but you should let Kaitlyn know when you will be out of the office for longer than 1 day. When possible, try to align your vacations with university holiday periods (this may be necessary if you are taking or teaching courses). Please set up out-of-office notifications on e-mail and Slack.

## Research integrity

Mistakes happen. For example, you may make a coding error that accidentally changes your findings. It is always best to bring up this mistakes as soon as you recognize them, so that we can collectively decide how to proceed. 

As a group, we should aim to reduce errors through data quality control checks, peer review of code among lab members, and frequently asking questions of each other when we are uncertain about data or methodology.

Under no circumstances should you fabricate data or manipulate research to obtain a certain result. If you are feeling any pressure to do so in order to make satisfactory progress, or have begun to go down this path and are having second thoughts, please talk to Kaitlyn immediately. 

This is (hopefully!) unlikely to be an issue in our research group, but should it come to light that you are engaging in dishonest research practices and hiding them from the group, there may be disciplinary action through UBC. This violation of trust will likely mean the end of your time in the Gaynor Lab.

See UBC resources:

+ [UBC's Scholarly Integrity Policy](https://responsible.research.ubc.ca/about/scholarly-integrity-initiative/ubcs-scholarly-integrity-policy)
+ [UBC Academic Honesty & Standards](https://www.grad.ubc.ca/current-students/student-responsibilities/academic-honesty-standards)
+ [UBC Intellectual Property](https://www.grad.ubc.ca/current-students/student-responsibilities/intellectual-property)
+ [UBC avoiding Plagiarism](https://www.grad.ubc.ca/current-students/student-responsibilities/dealing-plagiarism)