# Lab philosophy and code of conduct {#philosophy}

*This section on lab philosophy and code of conduct is taken almost entirely verbatim from [The Faylab Lab Manual](https://thefaylab.github.io/lab-manual/), because it resonated so fully with me. It is to be revisited with Gaynor Lab as it grows, so that we can collectively define our own philosophy and culture.*

## Lab philosophy

As part of our core lab culture, we:  

* Ask for help, and share our learning
* Make ourselves available
* Come prepared and engage
* Celebrate accomplishments (ours & those of others)
* Sustain a positive, safe learning environment
* Have an interdisciplinary (open) mindset
* Are mindful of our own biases
* Plan with intention, and follow through
* Foster inclusivity within our group and greater community
* Promote and sustain healthy work-life integration
* Practice radical candor
* Acknowledge and give credit to other lab member’s work

##### Ask for help, and share your learning {-}

We are all learners, and most of our learning is done from each other. It is inefficient to struggle through problems alone. Ask for and give assistance with appropriate cognizance of the value of your time and the time of the person you are asking. You are not the first or last person to encounter a problem. When you identify a problem, add an issue to the appropriate GitHub repository, and update it with solutions when it is resolved. Also consider sharing it with the larger community by tweeting, leading and sharing at a lab meeting, or running a workshop.  

##### Make yourself available {-}

Be responsive to communication, and make time for things that address longer term goals, even when busy. For example, do not skip on things like attending seminars just because you have a big deadline looming. Note that being available does not mean that you are available 24/7 - this is not expected. Because as a group we value the role of collaboration and interaction in improving our work, it is typically expected that you be available in the lab/office during normal business hours for some time during the week. However, note that, for 2022-2023, remote work is fine given that we are spatially dispersed and that the COVID-19 pandemic is still underway.

##### Come prepared and be engaged {-}

Value your time. Be present during lab and individual meetings, and come to your work ready to do your work. Contribute and participate in planning and lab discussions. When it is your turn to run a meeting, come with an agenda and be prepared with questions. Aim to view meetings as events that contribute to your work and productivity, rather than taking away from them.  

##### Celebrate accomplishments (yours & others) {-}

You and your colleagues work hard. Things don’t always go exactly as you plan. Be supportive and proud of yourself and your peers when you accomplish things. We are not competing with each other - someone else’s success does not mean your failure. Share your accomplishments with others!  

##### Sustain a positive, safe learning environment {-}

Everyone learns something for the first time at some time, and people learn in different ways. Expressing that you don’t know something is OK, and we understand that this can make someone feel vulnerable. We strive to maintain a culture that allows for and encourages this vulnerability. Community members should not be disparaged for not knowing things, and in addition, should not be disparaged for knowing things or wanting to learn.  

##### Have an interdisciplinary (open) mindset {-}

We work on problems that span multiple disciplines. Co-creation of knowledge requires transdisciplinary approaches that can result in solutions that would not be possible with siloing. You will be collaborating with others who have different types of expertise, values, and terminology. Trust the expertise of others and actively seek feedback recognizing the importance of specialization.     

##### Be mindful and aware of your own biases {-}

We all have biases that are inherent and can not be removed, but we can still work on both being less biased, and more aware of bias in ourselves and others. Periodically [check in on your biases](https://medium.com/better-humans/cognitive-bias-cheat-sheet-55a472476b18).  

##### Plan with intention, and follow through {-}

Be organized and adaptable. Things don’t always go as planned and that’s OK. Planning can help you adapt when they don’t (see Come Prepared). Find a program/project management approach that works for you; being organized can reduce stress immensely and help you progress with your goals.  

##### Foster inclusivity within our group and greater community {-}

Part of our lab culture is that we are good citizens of our community, we take on leadership roles within our departments, we are supportive of others in our community during their milestones, we actively participate in departmental events, and perform outreach. Work with Kaitlyn when crafting your individual mentoring/development plans to identify what you want to aim your efforts at.  

##### Promote and sustain healthy work-life integration {-}

Our scientific research is not the only important thing in our lives, and publishing research is not the only mechanism by which to provide science and support our communities. We recognize the importance of our other commitments in keeping us healthy (mentally and physically) and bring our whole selves to our efforts. Try not to normalize overwork or being busy as achievement or status.  

##### Practice radical candor {-}

We care personally while also challenging directly. Be honest when communicating, accept critical (but kind) feedback, and give the same to others. View relationships within the group as collaborative rather than evaluative. Don’t take constructive criticism personally.  

##### Acknowledge and give credit {-}

Working as part of a team, we will often (always?) be building on work done by others, receive assistance with work (see “Ask for help”), and using others’ words, code, content. Include acknowledgement and give credit for those contributions, in all forms of communication. We share content and code within the group with this expectation. One easy approach is to include hyperlinks to the work of others or their social media in your work. This also helps to amplify their voice and work as well as yours.  

## Code of conduct

A _Code of Conduct_ is a set of basic ground rules that we ask participants in lab spaces to follow. The goal is to create an open and inclusive space for our work that helps us achieve our collective goals. Along with our lab culture/philosophy, it also provides a benchmark for self-evaluation and helps better define our identity as a community. 

__We expect all lab members to adhere to the policies and guidelines outlined here.__  

### Short version

The Gaynor Lab is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, age, race, or religion. We do not tolerate harassment of participants in any form and prioritize marginalized people’s safety over privileged people’s comfort.  

This code of conduct applies to all Gaynor Lab spaces, including group and individual meetings (face to face and remote), workshops, social events, email correspondence, and web channels and code repositories, both online and off. Anyone who violates this code of conduct may be sanctioned and referred to the university’s academic policies.

### Longer version

The Gaynor Lab is dedicated to providing a harassment-free experience for everyone. We do not tolerate harassment of group members or others in our larger communities in any form. Bullying is unwanted, aggressive behavior that involves a real or perceived power imbalance. [UBC](https://bullyingandharassment.ubc.ca) provides definitions and examples of bullying and harassment.  

This code of conduct applies to all Gaynor Lab spaces, including group and individual meetings (face to face and remote), workshops, social get togethers, email correspondence, and web channels and code repositories, both online and off. Anyone who violates this code of conduct may be sanctioned and referred to the university’s academic policies.  

Some Gaynor Lab spaces may have additional rules in place, which will be made clearly available to participants. Participants are responsible for knowing and abiding by these rules.  

Harassment includes:  

* Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, age, race, or religion.  
* Unwelcome comments regarding a person’s lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment.
* Deliberate misgendering or use of ‘dead’ or rejected names.
* Gratuitous or off-topic sexual images or behaviour in spaces where they’re not appropriate.
* Physical contact without consent or after a request to stop.
* Threats of violence.
* Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm.
* Deliberate intimidation.
* Stalking or following.
* Harassing photography or recording, including logging online activity for harassment purposes.
* Sustained disruption of discussion.
* Unwelcome sexual attention.
* Pattern of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others
* Continued one-on-one communication after requests to cease.
* Deliberate “outing” of any aspect of a person’s identity without their consent except as necessary to protect vulnerable people from intentional abuse.
* Publication of non-harassing private communication.  

The Gaynor Lab prioritizes marginalized people’s safety over privileged people’s comfort. The PI (Kaitlyn Gaynor) reserves the right not to act on complaints regarding:  

* ‘Reverse’ -isms, including ‘reverse racism,’ ‘reverse sexism,’ and ‘cisphobia’
* Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you.”
* Communicating in a ‘tone’ you don’t find congenial
* Criticizing racist, sexist, cissexist, or otherwise oppressive behavior or assumptions

### Reporting

If you are being harassed by a member of the Gaynor Lab, notice that someone else is being harassed, or have any other concerns, please contact the PI, Dr. Kaitlyn Gaynor, at [gaynor@zoology.ubc.ca](mailto:gaynor@zoology.ubc.ca). If you do not wish to contact Dr. Gaynor, please contact Department Chair (*include contact info*). We will respond as promptly as we can.  

Lab members who believe they have been subjected to any kind of discrimination that conflicts with the University of British Columbia's policies and/or the laws of the Province of British Columbia should seek assistance from a supervisor or an HR representative. You can find a link to university policies [here](https://equity.ubc.ca/resources/policies-reports/).

This code of conduct applies to Gaynor Lab spaces, but if you are being harassed by a member of the Gaynor Lab or another member of the community outside our spaces, we still want to know about it. We will take all good-faith reports of harassment by lab members seriously. This includes harassment outside our spaces and harassment that took place at any point in time.  

To protect our team members from abuse and burnout, we reserve the right to reject any report we believe to have been made in bad faith. Reports intended to silence legitimate criticism may be deleted without response.  

The above caveats noted, we will respect confidentiality requests for the purpose of protecting victims of abuse when possible. At our discretion, we may publicly name a person about whom we’ve received harassment complaints, or privately warn third parties about them, if we believe that doing so will increase the safety of the Gaynor Lab members or the general public. We will not name harassment victims without their affirmative consent.  

### Consequences

Participants asked to stop any harassing behavior are expected to comply immediately.  

If a participant engages in harassing behavior, Kaitlyn may take any action they deem appropriate, which includes referral to the Department Chair, and also including expulsion from all Gaynor Lab spaces.



### License and attribution

This anti-harassment policy from the [Faylab Manual](https://thefaylab.github.io/lab-manual/03-code-of-conduct.html), which is based on the [example policy created by the Geek Feminism community](https://geekfeminism.wikia.org/wiki/Community_anti-harassment).
